name: portfolio_elsa
description: "Creating my own portfolio website."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: '>=3.4.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.11
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Luciole
      fonts:
        - asset: assets/fonts/Luciole-Regular.ttf
        - asset: assets/fonts/Luciole-Regular-Italic.ttf
          style: italic
        - asset: assets/fonts/Luciole-Bold.ttf
          weight: 700
        - asset: assets/fonts/Luciole-Bold-Italic.ttf
          style: italic
          weight: 700

flutter_intl:
  enabled: true